name = "my-chat-agent"
main = "src/index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

# 定义绑定到Durable Objects
[[durable_objects.bindings]]
name = "Chat"
class_name = "Chat"

# Durable Objects迁移
[[migrations]]
tag = "v1"
new_sqlite_classes = ["Chat"]

# KV绑定 - 用于缓存marketplace数据
[[kv_namespaces]]
binding = "CHAT_CACHE"
id = "fbb83b8ff112439db85a23c99a8389d4" # 在实际部署时需要替换为真实的KV ID
preview_id = "ae10a746c5e84abcbe8e33cc6dfb0c08" # 在实际部署时需要替换为真实的KV预览ID

# 环境变量（本地开发时使用）
# 实际的密钥请通过Cloudflare Dashboard或wrangler secret命令设置
# [vars]
# MODEL_NAME = "gpt-4o-2024-11-20"

# 示例：如何为不同环境配置变量
[env.production]
# production特定配置
# vars = { MODEL_NAME = "gpt-4o-2024-11-20" } 